###############
# Information #
###############
name: Redstone
version: 1.0
website: https://www.frozenorb.net/
depend: [CommonLibs]
author: FrozenOrb Development Team
main: com.frozenorb.redstone.RedstonePlugin

############
# Commands #
############
commands:
  #Enviroment Command
  rsenviroment:
    description: Check the current redstone enviroment
    aliases: [rsenv]
  #Servers Command
  rsservers:
    description: Check the redstone servers
    aliases: [rsserver]