###############
# Information #
###############
name: Redstone
version: null
author: FrozenOrb Development Team

############
# Commands #
############
commands:
  #Donation Command
  enviroment:
    description: Check the current redstone enviroment
    aliases: [rsenv]