###############
# Information #
###############
name: Meetup
version: null
website: https://www.frozenorb.net/
author: FrozenOrb Development Team
main: com.frozenorb.meetup.MeetupPlugin

############
# Commands #
############
commands:
