###############
# Information #
###############
name: uHub
version: null
author: FrozenOrb Development Team

############
# Commands #
############
commands:
  #Spawn Command
  spawn:
    description: Teleport to the Hub spawn.
    aliases: []