#######################################################
#        __  __           _  _____       _ _          #
#       |  \/  |         | |/ ____|     (_) |         #
#   __ _| \  / | ___   __| | (___  _   _ _| |_ ___    #
#  / _` | |\/| |/ _ \ / _` |\___ \| | | | | __/ _ \   #
# | (_| | |  | | (_) | (_| |____) | |_| | | ||  __/   #
#  \__, |_|  |_|\___/ \__,_|_____/ \__,_|_|\__\___|   #
#     | |                                             #
#     |_|                                             #
#                                                     #
# MineHQ qModSuite Plugin Replica - By ThatKawaiiSam  #
#                                                     #
#######################################################

#Redis Settings
Redis:
  IP: 127.0.0.1
  Port: 6379
  Password: