#########################################################
#      _____          _     _                           #
#     |  __ \        | |   | |                          #
#     | |__) |___  __| |___| |_ ___  _ __   ___         #
#     |  _  // _ \/ _` / __| __/ _ \| '_ \ / _ \        #
#     | | \ \  __/ (_| \__ \ || (_) | | | |  __/        #
#     |_|  \_\___|\__,_|___/\__\___/|_| |_|\___|        #
#                                                       #
#                                                       #
#   MineHQ Redstone Plugin Replica - By ThatKawaiiSam   #
#                                                       #
#########################################################

#Server Name
Server-Name: NA-Hub-1

#Server Group
Server-Group: Hub

#Server Stage
Server-Stage: Production

#Redis Settings
Redis:
  IP: 127.0.0.1
  Port: 6379
  Password: ""